# Diplomatura en IA - UP 
### Practico N°2 - Jun26
### Alumno: Gonzalez Marta Elizabeth 
### Notebook 06 - Procesamiento Final -

In [1]:
# Librerias

import pandas as pd
import numpy as np
import joblib

In [2]:
# Carga Modelo: 

best_model = joblib.load(
    "best_model.pkl"
)

print("Modelo cargado correctamente")

Modelo cargado correctamente

In [4]:
# Carga archivo entregado: 

df_pred = pd.read_excel(
    "../data/raw/smoking_prediction_entrega.xlsx"
)

In [5]:
print(df_pred.shape)

df_pred.head()

(5692, 26)

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar
0,27358,M,25,160,65,3.420139,0.045139,0.002778,0.041667,0.041667,...,3.041667,0.631250,0.041667,0.006250,0.750000,0.708333,0.708333,Y,0,Y
1,27364,M,30,180,80,3.458333,0.043056,0.006250,0.041667,0.041667,...,4.208333,0.587500,0.041667,0.041667,0.791667,1.125000,1.333333,Y,0,N
2,27368,M,55,165,60,3.416667,0.004861,0.005556,0.041667,0.041667,...,2.041667,0.625694,0.041667,0.006250,1.083333,1.291667,2.000000,Y,1,Y
3,27378,M,20,175,75,3.625000,0.045139,0.045139,0.041667,0.041667,...,3.708333,0.627083,0.041667,0.043750,0.833333,0.583333,0.458333,Y,0,N
4,27381,M,25,165,80,3.791667,0.043056,0.041667,0.041667,0.041667,...,6.625000,0.670833,0.041667,0.041667,1.250000,1.625000,1.958333,Y,1,Y

In [6]:
# Guardar ID para el archivo final

id_original = df_pred["ID"].copy()

In [7]:
# Eliminar ID

df_pred.drop(
    columns=["ID"],
    inplace=True
)

In [8]:
#Verificar estructura:

df_pred.columns.tolist()

['gender',
 'age',
 'height(cm)',
 'weight(kg)',
 'waist(cm)',
 'eyesight(left)',
 'eyesight(right)',
 'hearing(left)',
 'hearing(right)',
 'systolic',
 'relaxation',
 'fasting blood sugar',
 'Cholesterol',
 'triglyceride',
 'HDL',
 'LDL',
 'hemoglobin',
 'Urine protein',
 'serum creatinine',
 'AST',
 'ALT',
 'Gtp',
 'oral',
 'dental caries',
 'tartar']

In [9]:
print(df_pred.shape)
print(df_pred.columns.tolist())

(5692, 25)
['gender', 'age', 'height(cm)', 'weight(kg)', 'waist(cm)', 'eyesight(left)', 'eyesight(right)', 'hearing(left)', 'hearing(right)', 'systolic', 'relaxation', 'fasting blood sugar', 'Cholesterol', 'triglyceride', 'HDL', 'LDL', 'hemoglobin', 'Urine protein', 'serum creatinine', 'AST', 'ALT', 'Gtp', 'oral', 'dental caries', 'tartar']

In [10]:
'BMI' in df_pred.columns

False

In [11]:
'WHR' in df_pred.columns

False

In [12]:
'chol_hdl_ratio' in df_pred.columns

False

In [13]:
'tri_hdl_ratio' in df_pred.columns

False

In [14]:
print(df_pred.shape)
print(df_pred.columns.tolist())

(5692, 25)
['gender', 'age', 'height(cm)', 'weight(kg)', 'waist(cm)', 'eyesight(left)', 'eyesight(right)', 'hearing(left)', 'hearing(right)', 'systolic', 'relaxation', 'fasting blood sugar', 'Cholesterol', 'triglyceride', 'HDL', 'LDL', 'hemoglobin', 'Urine protein', 'serum creatinine', 'AST', 'ALT', 'Gtp', 'oral', 'dental caries', 'tartar']

In [15]:
df_pred["BMI"] = (
    df_pred["weight(kg)"] /
    ((df_pred["height(cm)"] / 100) ** 2)
)

df_pred["WHR"] = (
    df_pred["waist(cm)"] /
    (df_pred["height(cm)"] / 100)
)

df_pred["chol_hdl_ratio"] = (
    df_pred["Cholesterol"] /
    df_pred["HDL"]
)

df_pred["tri_hdl_ratio"] = (
    df_pred["triglyceride"] /
    df_pred["HDL"]
)

In [16]:
print(df_pred.shape)

(5692, 29)

In [17]:
print(df_pred.columns.tolist())

['gender', 'age', 'height(cm)', 'weight(kg)', 'waist(cm)', 'eyesight(left)', 'eyesight(right)', 'hearing(left)', 'hearing(right)', 'systolic', 'relaxation', 'fasting blood sugar', 'Cholesterol', 'triglyceride', 'HDL', 'LDL', 'hemoglobin', 'Urine protein', 'serum creatinine', 'AST', 'ALT', 'Gtp', 'oral', 'dental caries', 'tartar', 'BMI', 'WHR', 'chol_hdl_ratio', 'tri_hdl_ratio']

### Genera predicciones

In [18]:
# Generar predicciones:

predicciones = best_model.predict(
    df_pred
)

print(predicciones[:20])

[1 1 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 1 1]

In [19]:
# Verificar distribución

pd.Series(predicciones).value_counts()

0    3520
1    2172
Name: count, dtype: int64

In [20]:
print(df_pred.shape)

(5692, 29)

In [21]:
predicciones = best_model.predict(df_pred)

print(predicciones[:20])

[1 1 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 1 1]

In [22]:
pd.Series(predicciones).value_counts()

0    3520
1    2172
Name: count, dtype: int64

In [23]:
# Crear archivo de salida

resultado = pd.DataFrame({
    "smoking_prediction": predicciones
})

resultado.to_csv(
    "../data/processed/predicciones_finales.csv",
    index=False
)

resultado.head()

   smoking_prediction
0                   1
1                   1
2                   1
3                   0
4                   0

In [24]:
resultado = pd.DataFrame({
    "ID": id_original,
    "smoking_prediction": predicciones
})

resultado.to_csv(
    "../data/processed/predicciones_finales_ide.csv",
    index=False
)

In [25]:
resultado.head()

      ID  smoking_prediction
0  27358                   1
1  27364                   1
2  27368                   1
3  27378                   0
4  27381                   0

In [27]:
resultado.shape

(5692, 2)